name = "UnitfulDistributions"
uuid = "0f7e2b2a-29fa-49f7-8192-6450bd768ba8"
authors = ["kcarloni <kcarloni@g.harvard.edu>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Distributions = "0.25.120"
Unitful = "1.22.1"
